# Site settings
title: Akash TP 
twitter_username: _akash_tp
name: Akash TP

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: Twitter
   url: https://twitter.com/_akash_tp
 - title: GitHub
   url: https://github.com/Akashtp
 - title: LinkedIn
   url: https://www.linkedin.com/in/akashtp/

#Any buzzword skills you want to include
skills:
 - Python 
 - OpenCV
 - Product management
 - Java
 - SQL
 - Machine learning
 - Android Development
 
#Work experience is required
roles:
 - title: Software Engineer 
   start: 2022
   end: Ongoing
   employer: Tata ELXSI
   
 - title: Freelance Software Developer
   start: 2020
   end: 2022
   employer: Self

 - title: Software Developer
   start: 2019
   end: 2020
   employer: Perfect Fit Systems Private Limited
   
 - title: Backend Developer
   start: 2018
   end: 2019
   employer: Predict.ai (Self Employed)
   
   
#Education is required
education:
 - level: Bachelor of Technology (B.Tech)
   date: 2019
   subject: Information Technology 
   school: Cochin University Of Science And Technologies.

#List of interesting Github repo/projects to include - optional
github:
 - Akashtp/tensorflow
 - Akashtp/Python
 - Akashtp/Coursera-Machine-Learning-Stanford
 - Akashtp/Python-Projects
 - Akashtp/android-xellon
 - Akashtp/ML
 - Akashtp/java-samples
 - Akashtp/materials
 - Akashtp/gryds
 - Akashtp/android-samples
 - Akashtp/Akashtp.github.io


intro: |
  I am a Software Engineer with 2 years experience working at Tata Elxsi.Currently I am working as in data analytics field. I have primarily worked on the Python, but have worked across a broad range of technologies thereon: Java, and Android. Currently I am
  using MySQL, python, java and bash scripting for my work.<br/><br/>
  I enjoy building interesting products, with a good Product Management focus and a good emphasis on good engineering principles and clean code.<br/><br/>
  
